[agent]
  interval = "2s"
  flush_interval = "2s"

[[inputs.mqtt_consumer]]
  servers = ["tcp://mqtt:1883"]
  topics = ["gateway/v1/readings"]
  qos = 0
  data_format = "json_v2"

  [[inputs.mqtt_consumer.json_v2]]
    measurement_name = "sensor"

    timestamp_path = "timestamp"
    timestamp_format = "2006-01-02T15:04:05.999999999Z07:00"

    [[inputs.mqtt_consumer.json_v2.tag]]
      path = "device.id"
      rename = "device_id"

    [[inputs.mqtt_consumer.json_v2.tag]]
      path = "device.type"
      rename = "device_type"

    [[inputs.mqtt_consumer.json_v2.object]]
      path = "data"
      disable_prepend_keys = true

      [[inputs.mqtt_consumer.json_v2.object.field]]
        path = "*.value"
        type = "float"

[[outputs.influxdb_v2]]
  urls = ["http://influxdb:8086"]
  token = "${INFLUXDB_TOKEN}"
  organization = "${INFLUXDB_ORG}"
  bucket = "${INFLUXDB_BUCKET}"
