services:
  mqtt:
    image: eclipse-mosquitto:latest
    container_name: iot_mqtt
    restart: unless-stopped

    ports:
      - "1883:1883"

    volumes:
      - ../services/mqtt/config/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
