services:
  mqtt:
    image: eclipse-mosquitto:latest
    container_name: iot_mqtt
    restart: unless-stopped

    ports:
      - "1883:1883"

    volumes:
      - ../services/mqtt/config/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro

  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    container_name: iot_homeassistant
    restart: unless-stopped

    ports:
      - "8123:8123"

    volumes:
      - ../services/homeassistant:/config

    environment:
      - TZ=Asia/Tokyo
