[project]
name = "ai-agent"
version = "0.1.0"
description = "AI agent for IoT home assistant"
readme = "README.md"
authors = [
    { name = "joi0046", email = "220693654+joi0046@users.noreply.github.com" }
]
requires-python = ">=3.14"
dependencies = [
    "influxdb-client>=1.50.0",
]

[project.scripts]
ai-agent = "ai_agent:main"

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"
